# Generated by Django 5.1.2 on 2024-10-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentorg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='middlename',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
